### ISSUE TITLE
[Note Enhancement] Provide support for multiple categories for a note

### ISSUE THREAD

**Issue by krnekhelesh** [ctriantaf/cnotes-ubuntu-touch#10]
In the create new note page, the category is represented by a button which you press the category button which displays a popover. However it is quite possible for a note to be in multiple categories. So something similar to the tag feature needs to be implemented for the category as well.

**Comment by ctriantaf** [comment]
I though that too but I rejected it. The reason is that Category should be one because categories are more generally and the user could filter the notes with tags. Tags are more specific than categories.
What do you believe?

**Comment by krnekhelesh** [comment]
Thinking about it more, you are right. Tags will provide that finer detail. In that case, why not replace the button with the list view. The big orange button is not really ideal design wise. You could use an option selector as shown at http://design.ubuntu.com/apps/building-blocks/option-selector. The SDK provides this with a ListView valueSelector. You could check the UITK gallery to see what I mean.

**Comment by ctriantaf** [comment]
Now we're talking! I'll do that :dancers:

**Comment by ctriantaf** [comment]
Fixed on commit 0ab873e
