### ISSUE TITLE
[Note Enhancement] Add support for markdown

### ISSUE THREAD

**Issue by krnekhelesh** [ctriantaf/cnotes-ubuntu-touch#12]
It is natural for users to want to edit their text style to bold, italics, underline etc. This can provide a powerful enhancement to the notes feature. One way of doing this is by using markdown syntax or html tags <b></br> etc.

**Comment by ctriantaf** [comment]
I was able to add Markdown support for the TextField but it seems that TextArea (note's body) doesn't support rich text... It says at the docs that it supports but I can't get it to work

**Comment by ctriantaf** [comment]
Ok, done ;)

**Comment by krnekhelesh** [comment]
Can you close a bug after you push the code to trunk? This way a user can test it also confirm if necessary.

**Comment by ctriantaf** [comment]
There are some small bugs to fix. Give me some time and I'll push

**Comment by ctriantaf** [comment]
Try it :)

**Comment by krnekhelesh** [comment]
I get an error message when trying to run it. 
file:///home/krnekhelesh/AppShowdown2013/cnotes-ubuntu-touch/Storage.js:23: Error: no such table: categories Unable to execute statement

It opens the app, but I cannot save any note. It gives error
file:///home/krnekhelesh/AppShowdown2013/cnotes-ubuntu-touch/CreateNotePage.qml:32: TypeError: Cannot read property '0' of undefined

**Comment by ctriantaf** [comment]
In MainPage around line 9 is deleteDatabase() commented?

**Comment by krnekhelesh** [comment]
not commented

**Comment by ctriantaf** [comment]
Ok, commented it and try again
