### ISSUE TITLE
Move Create button to the toolbar

### ISSUE THREAD

**Issue by krnekhelesh** [ctriantaf/cnotes-ubuntu-touch#13]
The toolbar is available to do provide actions such as Create, Edit etc. It shouldn't be part of the new note page. You can also make it clever by showing the toolbar persistently on the desktop while hiding it on the phone by default.

You can lock the toolbar by using the properties such as,

locked: true
opened: true

**Comment by ctriantaf** [comment]
If I put the Create button in the toolbar the user has to do an extra swipe to create it..
Regarding UI its definitely a good choice but I don't know about functionality..

**Comment by krnekhelesh** [comment]
Agreed. But you can remove that extra swipe by making the toolbar persistent (doesnt hide automatically). This way you get the best of both worlds (UI and funtionality). The core apps currently use this trick.

**Comment by ctriantaf** [comment]
Agreed! Consider it done ;)

**Comment by ctriantaf** [comment]
I have a problem with that! I added in the visible: true and locked: true in the tools in createPage but when I open the createPage using the Add button in the mainView's toolbar the last is getting persistent and not the tools from createPage.. Did you understand? :P

**Comment by krnekhelesh** [comment]
I am not familiar with your code base, but it should work. I am currently doing that in the clock app  and it works fine. You need to set the properties to false when you exit the createPage. Also the property should be opened and not the visible property that you are using. Have you defined each toolbar in its own page? If you did that then, when showing the createPage, it should show that page's toolbar when swiped up.

**Comment by ctriantaf** [comment]
Sorry, I did a mistake in the above comment, I used opened and not visible.
Yes, every toolbar in a different page. Oh you meant to make the toolbar persistent only when it was swiped up? Not from the beginning?

**Comment by krnekhelesh** [comment]
If you defined the toolbar in the createPage and set its properties correctly, then it should automatically make the toolbar persistent when you push that page to the pagestack. This is also why I find this a bit odd that it doesnt work for you. Which file is this create toolbar in? I am unable to find it in your code due to my lack of understanding.

**Comment by krnekhelesh** [comment]
Okay so I branched your code and fixed it :). I do not know how to share to github, so I guess I will have to meet you on IRC or google+ hangout to explain the situation on how I fixed it. There are some inherent flaws that need to be addressed asap. Let me know if you are available for this meetup.

**Comment by ctriantaf** [comment]
I'm on ubuntu-app-devel now, nickname: clepto
