### ISSUE TITLE
Incorrect usage of positioning elements in ArchivesPage.qml

### ISSUE THREAD

**Issue by krnekhelesh** [ctriantaf/cnotes-ubuntu-touch#14]
Taking a brief look at your code structure, I noticed that you are using a pagestack where you push pages such as ArchivesPage, notespage etc etc. This is correct. However when looking at your ArchivesPage.qml, I noticed some coding errors that I have described below.

The code snippet that is wrong is shown below,

Page {
    id: archivePage
    height: parent.height

```
property string pos

Header {
    id: header
    title: i18n.tr("Archives")
}

ListView {
    id: archivesView
    height: parent.height - header.height
    width: parent.width
    anchors {
        top: header.bottom
        left: parent.left
        right: parent.right
        margins: units.gu(2)
    }
```

First of all, you **do not need** to state the header property of a page. You can remove the entire `Header {}` code and replace it with just,

`title: i18n.tr("Archives")`

Second, you **do not need** to explicitly state the height of a page. It will automatically take the full width and height of the parent.

Third, in the ListView, you have set the height, width and also the anchor properties. Setting the anchor properties alone would do the job. In this case,

`anchors {
            fill: parent
            margins: units.gu(2)
        }`

I am guessing you did this in the other pages as well. You might want to correct them as well before proceeding. Also take a look at the API examples and other application code.

**Comment by ctriantaf** [comment]
I see. Thanks for pointing that out. I'll make the changes!

**Comment by krnekhelesh** [comment]
You can also remove the definitions height: parent.height that you declared when you included the archivespage, notespage in the mainPage definition.

**Comment by ctriantaf** [comment]
Noted
