### ISSUE TITLE
Unable to create new task after updating app

### ISSUE THREAD

**Issue by iBelieve** [ctriantaf/cnotes-ubuntu-touch#15]
When I try to run the app, I can't create a new note, and I get this error:

```
unity::action::ActionManager::ActionManager(QObject*):
    Could not determine application identifier. HUD will not work properly.
    Provide your application identifier in $APP_ID environment variable.
file:///home/mspencer/Programs/showdown/cnotes-ubuntu-touch/Storage.js:106: Error: no such column: archive Unable to execute statement
file:///home/mspencer/Programs/showdown/cnotes-ubuntu-touch/Storage.js:34: Error: table notes has 4 columns but 7 values were supplied Unable to execute statement
```

It looks like you've changed the format database since I last ran your app. Where can I find the database to delete it?

**Comment by ctriantaf** [comment]
If you have latest commit then in MainPage.qml around line 9 uncomment the Storage.deleteDatabase() and run, then close, comment it and re-run, so the database isn't deleted every time you open the app,

**Comment by iBelieve** [comment]
Thanks, that worked.
