### ISSUE TITLE
Old note entries visible when creating a new note

### ISSUE THREAD

**Issue by krnekhelesh** [ctriantaf/cnotes-ubuntu-touch#2]
I created a note and filled in some data like the title, tags, description etc and saved it. Then when I tried adding a new note, the old note contents were still there in the new note page. It has to be cleared when the old note was saved.

**Comment by ctriantaf** [comment]
Man, I just filled that bug here a second ago :P
Already on it!

**Comment by krnekhelesh** [comment]
lol!

**Comment by ctriantaf** [comment]
Pushed!
