### ISSUE TITLE
CNote needs a background gradient 

### ISSUE THREAD

**Issue by krnekhelesh** [ctriantaf/cnotes-ubuntu-touch#4]
The current grey color (default) is dull and should be replaced with something more colorful yet not too distracting. The Ubuntu SDK provides a very easy way to add background gradients.

Basically 3 lines on code in the Mainview,

headerColor: "#57365E"
backgroundColor: "#A55263"
footerColor: "#D75669"

Changes these colors to your liking :)

**Comment by ctriantaf** [comment]
Oh I was wondering about that and I wanted to ask! Nice, i'll do it! Thanks

**Comment by krnekhelesh** [comment]
We got you covered :)

**Comment by ctriantaf** [comment]
Pushed!
