### ISSUE TITLE
Margins need some tweaking

### ISSUE THREAD

**Issue by krnekhelesh** [ctriantaf/cnotes-ubuntu-touch#8]
There are many places in the application where the margins are not being used resulting in an element being very close to the edge. One example of this is the tag dialog. When you press the tag button to show the popup, the saved tag are listed but they have 0 margin. Margins are needed here to make it look better.

**Comment by ctriantaf** [comment]
I know about this one. I have tried with horizontalCenter on the GridView but its not working. I'll try with margin

**Comment by krnekhelesh** [comment]
I was thinking about asking you to use anchors.leftMargin, anchors.rightMargin when I realised that this can all be done automatically using a row :)

You can set the row properties to be something like,
row {
  spacing: units.gu(1)
  anchors { fill: parent; topMargin: units.gu(1); bottomMargin: units.gu(1); leftMargin: units.gu(1); rightMargin: units.gu(1); }
}

I think this should do the trick.

**Comment by ctriantaf** [comment]
GridView (http://qt-project.org/doc/qt-5.0/qtquick/qml-qtquick2-gridview.html) doesn't have a row property except you're referring to a different element.

**Comment by krnekhelesh** [comment]
In that case apply the anchor properties I mentioned above to the gridview then.

GridView {
  anchors { fill: parent; topMargin: units.gu(1); bottomMargin: units.gu(1); leftMargin: units.gu(1); rightMargin: units.gu(1); }
}
