### ISSUE TITLE
Adaptive layout for phone, tablet and desktop

### ISSUE THREAD

**Issue by krnekhelesh** [ctriantaf/cnotes-ubuntu-touch#9]
The Ubuntu SDK provides support for dynamic layout. By looking at the app window size, one can dynamically adjust the UI to reflect that. For instance in landscape mode, you could could take advantage of the width. This will earn extra points in the contest.

**Comment by ctriantaf** [comment]
Already on the ToDo list. Is there any examples I could look at?

**Comment by krnekhelesh** [comment]
You could look at the SDK API Docs or applications like Ubuntu tasks, memories written by other developers. You can find their code repository link at https://wiki.ubuntu.com/Touch/AppShowdownList

**Comment by ctriantaf** [comment]
Thanks!

**Comment by iBelieve** [comment]
If it agrees with your license, you're welcome to use my [Sidebar](https://github.com/iBeliever/tasks-app/blob/master/components/Sidebar.qml) class (or whatever it should be called in QML). I wrote it to be reused, so it doesn't have app-specific code in it. All you do is set the `expanded` property, and it will handle the animation of sliding in or out.

**Comment by iBelieve** [comment]
I've created a separate repository for extra UI components not in the Ubuntu UI Toolkit. If you're interested in using the Sidebar class I made, the repository is https://github.com/iBeliever/ubuntu-ui-extras. I plan on adding other components in the future.

**Comment by ctriantaf** [comment]
Thanks!

**Comment by ctriantaf** [comment]
I have problem with Conditional layouts... You can see here https://plus.google.com/106994414439340279133/posts/gnFB6juE4sT

**Comment by ctriantaf** [comment]
Done
